---
-
  hosts: all
  name: "display os version"
  tasks:
    -
      name: "display OS version"
      shell: "cat /etc/redhat-release  >> /tmp/2.txt"
      when: ('ansible_host == \"192.168.0.109\"')
