---
-
  hosts: all
  name: "display os version"
  tasks:
    -
      name: "display OS version"
      shell: "cat /etc/redhat-release  >> /tmp/5.txt"
      when: (ansible_host == "192.168.0.109") and  (ansible_distribution_file_variety  == "RedHat")
